// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getWithin
SEXP getWithin(SEXP alpha_, SEXP X_);
RcppExport SEXP _RECP_getWithin(SEXP alpha_SEXP, SEXP X_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    rcpp_result_gen = Rcpp::wrap(getWithin(alpha_, X_));
    return rcpp_result_gen;
END_RCPP
}
// getBetween
SEXP getBetween(SEXP alpha_, SEXP X_, SEXP Y_);
RcppExport SEXP _RECP_getBetween(SEXP alpha_SEXP, SEXP X_SEXP, SEXP Y_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y_(Y_SEXP);
    rcpp_result_gen = Rcpp::wrap(getBetween(alpha_, X_, Y_));
    return rcpp_result_gen;
END_RCPP
}
// split_re
SEXP split_re(SEXP s_, SEXP e_, SEXP D_, SEXP min_size_);
RcppExport SEXP _RECP_split_re(SEXP s_SEXP, SEXP e_SEXP, SEXP D_SEXP, SEXP min_size_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type s_(s_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type e_(e_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type D_(D_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type min_size_(min_size_SEXP);
    rcpp_result_gen = Rcpp::wrap(split_re(s_, e_, D_, min_size_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RECP_getWithin", (DL_FUNC) &_RECP_getWithin, 2},
    {"_RECP_getBetween", (DL_FUNC) &_RECP_getBetween, 3},
    {"_RECP_split_re", (DL_FUNC) &_RECP_split_re, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RECP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
