# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getWithin <- function(alpha_, X_) {
    .Call(`_RECP_getWithin`, alpha_, X_)
}

getBetween <- function(alpha_, X_, Y_) {
    .Call(`_RECP_getBetween`, alpha_, X_, Y_)
}

split_re <- function(s_, e_, D_, min_size_) {
    .Call(`_RECP_split_re`, s_, e_, D_, min_size_)
}

dista_cpp <- function(X_, grid_) {
    .Call(`_RECP_dista_cpp`, X_, grid_)
}

Dist_cpp <- function(X_) {
    .Call(`_RECP_Dist_cpp`, X_)
}

